### ISSUE TITLE
Item Shops Bugs Out After Heavy Usage

### ISSUE THREAD

**Issue by LoJoSho** [7sat/DShop3#55]
After heavy usage of an item shop, it can "bug out", causing you to be unable to buy/sell items from the menu until reopening the trade window. This is shown in the clicking on an item and it turns to a black glass pane. 

No errors are shown if this happens.

https://i.imgur.com/7qLbWFE.gif

**Comment by 7sat** [comment]
can you give me your shop.yml file?
I couldn't reproduce it.

**Comment by LoJoSho** [comment]
Of course, it took quite a bit (~5m) for me to even get it to replicate once,

https://paste.gg/p/anonymous/76531b0787d74aae8efe3f995054b7e0

**Comment by 7sat** [comment]
While trying to reproduce, I looked closely at the git file again, and it is strange that there is an item 'black_stained_glass_pane'.
DynamicShop plugin does not create 'black_stained_glass_pane' in that UI.
It is possible that another plugin on the server is causing the problem.

**Comment by LoJoSho** [comment]
Hmm, I don't see why any plugin would do that on my server, however, I shall get back to you once I look through them all.

**Comment by 7sat** [comment]
The way store data is handled is now improved.
