### ISSUE TITLE
Closing out of an Item opens the Item Palette instead of going back to the Shop...

### ISSUE THREAD

**Issue by Chris6ix** [7sat/DShop3#65]
**Minecraft version**
1.18.1

**Plugin version**
3.5.0

**Describe the bug**
When you edit an item in the Shop, but instead of saving it, close it, it opens the item palette instead of closing and going back to the Shop you were before

**To Reproduce**
/\

**Expected behavior**
/\

**Comment by 7sat** [comment]
It was intentional when I first made it, but now it is inconvenient. It would be better to just go back to the store page.

**Comment by 7sat** [comment]
https://github.com/7sat/DShop3/commit/08762a98a8db8fd13805f9c84e72c058c8df65f3

**Comment by Chris6ix** [comment]
Thanks👍
