### ISSUE TITLE
Adding an Item to a page with the item palette makes it go to the 1st page

### ISSUE THREAD

**Issue by Chris6ix** [7sat/DShop3#66]
**Minecraft version**
1.18.1

**Plugin version**
3.5.0

**Describe the bug**
When you add an item with the item palette to a Page in a Shop, the item goes to the 1st page of the Shop instead of the page you selected.
So basically issue #61 but with single items...

**To Reproduce**
/\

**Expected behavior**
/\

**Comment by 7sat** [comment]
I tested it on 3.5.0 and 3.109.0, but it does not reproduce.
(my server uses paper 1.18.2)

When I did, the item was added to the clicked position in both the newly created store and the existing store.
![image](https://user-images.githubusercontent.com/49030779/159162277-b13da190-22b9-4915-8da7-6a92b3e2673e.png)

**Comment by 7sat** [comment]
I accidentally pressed close.
