### ISSUE TITLE
[Suggestion] Improve Logging

### ISSUE THREAD

**Issue by Chris6ix** [7sat/DShop3#69]
The logging the plugin currently does is a bit useless and weird...it doesn't even show if the item was bought or sold, how much was sold/bought, and you have no possibility to find out if a player is for example selling a ton of duped items...you would have to manually check every log file all the time to find out such things.

It could be improved by showing if the item was bought or sold.
It could also log how much was bought or sold (e.g. 64)

Also, it would be extremely helpful (for smaller servers at least, big servers would probably have too much console spam then...) to see the player's purchases live in the console, without needing to manually check the log file (With a config option to disable/enable).

I also think that some logging it does is unnecessary:
-The coordinates of the player where he purchased the item...what use does that have? 
-That vault was used...what use does that have? 
-The date of the transaction, because the file itself already has the date on it. 
Maybe could have its own config options to decide what you want to log and what not? An example to show what I mean:

Currently, logs look like this:
`04-03-2022-23-24-16,MELON_SLICE,-64,147.24,vault,PLAYER_NAME`
This could be changed to:
`23-24-16,MELON_SLICE,AMOUNT,PLAYER_NAME`
if the server owner wants to :)

The live console log could be very simple and could look something like this: 
`PLAYER_NAME bought/sold ITEM AMOUNT` as you already have the time of the message in the console...

**Comment by 7sat** [comment]
>04-03-2022-23-24-16,MELON_SLICE,-64,147.24,vault,PLAYER_NAME

- In the example data above, -64 is not a coordinate. That means 64 items were sold to the store. (If purchased, it will be displayed as 64)
- 147.24 is the transaction amount. (In this example, it is the sum of money earned by selling items)
- In the case of 'vault', it is currently used to distinguish it from the point shop of Jobsreborn.

**Comment by 7sat** [comment]
Live logging seems like a good idea. Unfortunately, I have paused development.

**Comment by Chris6ix** [comment]
>In the example data above, -64 is not a coordinate. That means 64 items were sold to the store. (If purchased, it will be displayed as 64)
>147.24 is the transaction amount. (In this example, it is the sum of money earned by selling items)

Oh...okay now it makes more sense...I mistook that number for coordinates...
Thanks for explaining that :)

**Comment by 7sat** [comment]
[Related content has been updated.](https://github.com/7sat/DShop3/commit/cd691dabfa8775aca69ae541a5eb7b3ae930d669)

**Comment by Chris6ix** [comment]
> [Related content has been updated.](https://github.com/7sat/DShop3/commit/cd691dabfa8775aca69ae541a5eb7b3ae930d669)

Thank you very much :)
