### ISSUE TITLE
Restocking not working

### ISSUE THREAD

**Issue by Caleston** [7sat/DShop3#79]
**Minecraft version**
1.19 Paper

**Plugin version**
DynamicShop Premium v3.110.6

**Describe the bug**
Shop restocking is not working properly. It stops working on its own entirely, possibly upon restart (uncertain).
Turning stock stabiliziation off and back on fixes it temporarily (at least on short interval, uncertain about longer interval).
Could apply to stock fluctuation as well?
Prices on our server have been crashing hard and it is quite tedious to have to retoggle price recovery each day.

**To Reproduce**
Turn stock stabilization on.
Restart server.
= Stock no longer recovers.

**Expected behavior**
Stock stabilization continues normally, even after restart, as on older version.

**Comment by Caleston** [comment]
An update on this: it seems that the bug mostly exists with LONG INTERVAL price changes.
We kept very short interval stock stabilization and it has stayed on between restarts for days.

**Comment by 7sat** [comment]
https://www.spigotmc.org/resources/dshop-3-1-13-1-19-3.65603/update?update=486723
This is now fixed.
Thanks for the detailed explanation of the problem. Helped me a lot.
